name: Build and deploy Python app to Azure Web App - videoapp2

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !.git/
            !.github/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id:        ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id:        ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id:  ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}
          audience:         api://AzureADTokenExchange

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'videoapp2'
          slot-name: 'Production'
